### ISSUE TITLE
missing a way to check for status without closing the pipes

### ISSUE THREAD

**Issue by nevakrien** [Neko-Box-Coder/System2#6]
so with System2GetCommandReturnValueAsync if it is a success it closes all of the curent pipes which means all captured output is lost.
it would be nice to have a way to just check whats the current status.

**Comment by Neko-Box-Coder** [comment]
Yeah, you are right. #8 should fix it.

Saw your fix on Windows as well so I applied that too but haven't tested it yet.

The main example should cover all the functions now.

**Comment by nevakrien** [comment]
nice seems like we are improving things a lot :)
